DELETE http://localhost:8000/api/v1/post/4
Accept: application/json

###
GET http://localhost:8000/api/v1/posts/1
Accept: application/json

###
GET http://localhost:8000/api/v1/posts
Accept: application/json

###
PUT http://localhost:8000/api/v1/update-post
Content-Type: application/json

{
  "id": 1,
  "title": "Golang Book",
  "body": "A good book!"
}

###
POST http://localhost:8000/api/v1/create-post
Content-Type: application/json

{
  "title": "Go-1",
  "body": "Go book"
}

###

